version: "3.8"
services:
  apiusersmysql:
    build: .
    container_name: "api-users-mysql"
    depends_on:
      - mysql
    ports:
      - 8081:8081
    networks:
      - app_network
  mysql:
    image: mysql:8.0.30
    container_name: "mysql"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db_users
    ports:
      - 3307:3306
    volumes:
      - ./db-init:/docker-entrypoint-initdb.d
    networks:
      - app_network

networks:
  app_network:
    driver: bridge